title: GHWB Presidential Daily File
description: >-
  A chronological catalog of documents from the George H.W. Bush
  Presidential Daily File (1989–1993), curated from LinkedIn posts
  by James Graham Wilson.
theme: jekyll-theme-cayman
show_downloads: false
